---
title: "Analyzing the influnce of automatic transmission on miles per gallon"
author: "Jakob Schelbert"
date: "22 12 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
summary(mtcars)

mtcars[]

fit1 <- lm(mpg ~ am, data = mtcars)
fit2 <- lm(mpg ~ am + cyl, data = mtcars)
fit3 <- lm(mpg ~ am + cyl + disp, data = mtcars)
fit4 <- lm(mpg ~ am + cyl + disp + hp, data = mtcars)
fit5 <- lm(mpg ~ am + cyl + disp + hp + wt, data = mtcars)
fit6 <- lm(mpg ~ am + cyl + disp + hp + wt + qsec, data = mtcars)
anova(fit1, fit2, fit3, fit4, fit5, fit6)
fit4a <- lm(mpg ~ am + cyl + hp, data = mtcars)
fit5a <- lm(mpg ~ am + cyl + hp + wt, data = mtcars)
anova(fit1, fit2, fit4a, fit5a)
```

# load swiss data and
data(swiss)
# run linear regression on Fertility vs all other predictors
fit <- lm(Fertility ~ . , data = swiss)
# generate diagnostic plots in 2 x 2 panels
par(mfrow = c(2, 2)); plot(fit)

http://docs.ggplot2.org/0.9.3.1/fortify.lm.html
https://rpubs.com/therimalaya/43190

